"""Making item_id a unique key in plaid_items table and adding plaid_accounts table

Revision ID: 18313c73bf36
Revises: e7eec6765e2f
Create Date: 2026-06-23 23:26:24.959842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18313c73bf36'
down_revision: Union[str, Sequence[str], None] = 'e7eec6765e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_plaid_items_item_id'), 'plaid_items', ['item_id'], unique=True)
    op.create_table('plaid_accounts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mask', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['plaid_items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaid_accounts')
    op.drop_index(op.f('ix_plaid_items_item_id'), table_name='plaid_items')
    # ### end Alembic commands ###
