"""Add table for plaid

Revision ID: 735a6f97bc6b
Revises: d3c3a692b5be
Create Date: 2026-06-22 16:37:40.320925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '735a6f97bc6b'
down_revision: Union[str, Sequence[str], None] = 'd3c3a692b5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('institution_name', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaid_items')
    # ### end Alembic commands ###
