"""Adding support for curson in plaid_items table

Revision ID: 833ceb56eb38
Revises: cd06c9965e0b
Create Date: 2026-06-29 13:25:23.121617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '833ceb56eb38'
down_revision: Union[str, Sequence[str], None] = 'cd06c9965e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_items', sa.Column('cursor', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_items', 'cursor')
    # ### end Alembic commands ###
