"""Add account customization fields

Revision ID: cd06c9965e0b
Revises: 18313c73bf36
Create Date: 2026-06-24 16:23:42.279031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd06c9965e0b'
down_revision: Union[str, Sequence[str], None] = '18313c73bf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_accounts', sa.Column('custom_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plaid_accounts', sa.Column('classification_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_accounts', 'classification_type')
    op.drop_column('plaid_accounts', 'custom_name')
    # ### end Alembic commands ###
