"""Make columns optional in plaid_items table

Revision ID: e7eec6765e2f
Revises: 735a6f97bc6b
Create Date: 2026-06-22 17:04:22.288586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7eec6765e2f'
down_revision: Union[str, Sequence[str], None] = '735a6f97bc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plaid_items', 'institution_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('plaid_items', 'institution_name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plaid_items', 'institution_name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('plaid_items', 'institution_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
