"""Adding table to hold daily snapshot of holdings. Also add support for cash transactions

Revision ID: 778bcc15f23b
Revises: 7b9157bcfc49
Create Date: 2026-07-09 09:45:19.662375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778bcc15f23b'
down_revision: Union[str, Sequence[str], None] = '7b9157bcfc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(**kwargs) -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['daily_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_holdings_ticker'), 'snapshot_holdings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade(**kwargs) -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_holdings_ticker'), table_name='snapshot_holdings')
    op.drop_table('snapshot_holdings')
    # ### end Alembic commands ###
