"""Adding paycheck tables

Revision ID: c355eca1e6ad
Revises: 7aee448e3075
Create Date: 2026-07-19 14:56:45.847080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c355eca1e6ad'
down_revision: Union[str, Sequence[str], None] = '7aee448e3075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_portfolio_db() -> None:
    """Upgrade portfolio_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_current_positions_account_id'), 'current_positions', ['account_id'], unique=False)
    # op.drop_constraint(op.f('current_positions_ibfk_1'), 'current_positions', type_='foreignkey')
    # op.create_foreign_key(None, 'current_positions', 'accounts', ['account_id'], ['id'])
    # op.create_index(op.f('ix_daily_snapshots_account_id'), 'daily_snapshots', ['account_id'], unique=False)
    # op.drop_constraint(op.f('daily_snapshots_ibfk_1'), 'daily_snapshots', type_='foreignkey')
    # op.create_foreign_key(None, 'daily_snapshots', 'accounts', ['account_id'], ['id'])
    # op.drop_constraint(op.f('snapshot_holdings_ibfk_1'), 'snapshot_holdings', type_='foreignkey')
    # op.create_foreign_key(None, 'snapshot_holdings', 'daily_snapshots', ['snapshot_id'], ['id'])
    # op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    # op.drop_constraint(op.f('transactions_ibfk_1'), 'transactions', type_='foreignkey')
    # op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
    pass


def downgrade_portfolio_db() -> None:
    """Downgrade portfolio_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'transactions', type_='foreignkey')
    # op.create_foreign_key(op.f('transactions_ibfk_1'), 'transactions', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    # op.drop_constraint(None, 'snapshot_holdings', type_='foreignkey')
    # op.create_foreign_key(op.f('snapshot_holdings_ibfk_1'), 'snapshot_holdings', 'daily_snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')
    # op.drop_constraint(None, 'daily_snapshots', type_='foreignkey')
    # op.create_foreign_key(op.f('daily_snapshots_ibfk_1'), 'daily_snapshots', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # op.drop_index(op.f('ix_daily_snapshots_account_id'), table_name='daily_snapshots')
    # op.drop_constraint(None, 'current_positions', type_='foreignkey')
    # op.create_foreign_key(op.f('current_positions_ibfk_1'), 'current_positions', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # op.drop_index(op.f('ix_current_positions_account_id'), table_name='current_positions')
    # ### end Alembic commands ###
    pass


def upgrade_paycheck_db() -> None:
    """Upgrade paycheck_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paychecks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paychecks_pay_date'), 'paychecks', ['pay_date'], unique=False)
    op.create_table('paycheck_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paycheck_id', sa.Integer(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['paycheck_id'], ['paychecks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paycheck_line_items_category'), 'paycheck_line_items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade_paycheck_db() -> None:
    """Downgrade paycheck_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paycheck_line_items_category'), table_name='paycheck_line_items')
    op.drop_table('paycheck_line_items')
    op.drop_index(op.f('ix_paychecks_pay_date'), table_name='paychecks')
    op.drop_table('paychecks')
    # ### end Alembic commands ###

