"""Adding support for institute name

Revision ID: 7aee448e3075
Revises: b36b9bad545e
Create Date: 2026-07-12 14:49:51.900251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aee448e3075'
down_revision: Union[str, Sequence[str], None] = 'b36b9bad545e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(**kwargs) -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('institute', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade(**kwargs) -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'institute')
    # ### end Alembic commands ###
