"""Adding table to store current positions

Revision ID: 7b9157bcfc49
Revises: cd93b1b4d5d5
Create Date: 2026-07-08 16:28:53.941867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9157bcfc49'
down_revision: Union[str, Sequence[str], None] = 'cd93b1b4d5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(**kwargs) -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_cost_basis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'ticker', name='uq_account_ticker')
    )
    op.create_index(op.f('ix_current_positions_ticker'), 'current_positions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade(**kwargs) -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_positions_ticker'), table_name='current_positions')
    op.drop_table('current_positions')
    # ### end Alembic commands ###
