"""Creating Tables Paycheck

Revision ID: a17ae460b546
Revises: 7aee448e3075
Create Date: 2026-07-19 00:01:54.166548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a17ae460b546'
down_revision: Union[str, Sequence[str], None] = '7aee448e3075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(**kwargs) -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paycheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_date', sa.DateTime(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paycheck_pay_date'), 'paycheck', ['pay_date'], unique=False)
    op.create_table('paycheck_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paycheck_id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['paycheck_id'], ['paycheck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paycheck_line_item_category'), 'paycheck_line_item', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade(**kwargs) -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paycheck_line_item_category'), table_name='paycheck_line_item')
    op.drop_table('paycheck_line_item')
    op.drop_index(op.f('ix_paycheck_pay_date'), table_name='paycheck')
    op.drop_table('paycheck')
    # ### end Alembic commands ###
