"""adding support for stock split

Revision ID: b36b9bad545e
Revises: 3137ebc3838c
Create Date: 2026-07-10 13:07:41.128796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36b9bad545e'
down_revision: Union[str, Sequence[str], None] = '3137ebc3838c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(**kwargs) -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions MODIFY COLUMN transaction_type ENUM('BUY', 'SELL', 'DEPOSIT', 'WITHDRAW', 'SPLIT') NOT NULL;")
    # ### end Alembic commands ###


def downgrade(**kwargs) -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions MODIFY COLUMN transaction_type ENUM('BUY', 'SELL', 'DEPOSIT', 'WITHDRAW') NOT NULL;")
    # ### end Alembic commands ###
